In [1]:
import numpy as np
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Ridge, Lasso
import matplotlib.pyplot as plt
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import cross_val_score
from sklearn.metrics import r2_score
from sklearn.svm import SVR
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

In [15]:
X, y = fetch_california_housing(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

# POLYNOMIAL LINEAR REGRESSION

In [3]:
poly_features = PolynomialFeatures(degree=2, include_bias=False)
X_train_poly = poly_features.fit_transform(X_train)
X_test_poly = poly_features.fit_transform(X_test)

In [4]:
reg_X_train = LinearRegression()
reg_X_train = reg_X_train.fit(X_train_poly, y_train)
cross_val_score(reg_X_train, X_train_poly, y_train, scoring='neg_mean_squared_error')

array([-0.54313534, -0.43887106, -0.49162261, -6.30167361, -0.62006414])

In [5]:
y_pred = reg_X_train.predict(X_test_poly)
r2_score(y_test, y_pred)

0.6359115788077037

# POLYNOMIAL SUPPORT VECTOR REGRESSION

In [6]:
SVR_model = make_pipeline(StandardScaler(), SVR(kernel='poly', degree=2))
SVR_model = SVR_model.fit(X_train, y_train)
cross_val_score(SVR_model, X_train, y_train, scoring='neg_mean_squared_error')

array([-199.59561818,   -1.04675595,   -1.16492601,   -6.97806405,
         -1.2894135 ])

In [7]:
y_pred_SVR = SVR_model.predict(X_test)
r2_score(y_test, y_pred_SVR)

0.07922792546618274

#  RIDGE REGRESSION MODEL

In [8]:
ridge = Ridge(alpha =1.0)
ridge = ridge.fit(X_train, y_train)
cross_val_score(ridge, X_train, y_train, scoring='neg_mean_squared_error')

array([-0.56159259, -0.54151957, -0.50929902, -0.50575734, -0.51434351])

In [9]:
y_pred_ridge = ridge.predict(X_test)
r2_score(y_test, y_pred_ridge)

0.5910380033836857

# LASSO REGRESSION MODEL

In [10]:
lasso = Lasso(alpha=0.1)
lasso = lasso.fit(X_train, y_train)
cross_val_score(lasso, X_train, y_train, scoring='neg_mean_squared_error')

array([-0.63757815, -0.61795393, -0.58324341, -0.58542146, -0.59836517])

In [11]:
y_pred_lasso = lasso.predict(X_test)
r2_score(y_test, y_pred_lasso)

0.5291373575544269